# Dependencies
plugins:
  - jekyll-sitemap
  - jekyll-paginate

# Permalinks
permalink:           pretty

# Setup
url:                 http://misty0703.github.io

# Set to '' in case of hosting on GitHub pages,
# i.e. `http://<username>.github.io`
baseurl:             # http://misty0703.github.io

title:               misty0703

# Pagination
paginate:            5
paginate_path:       '/page-:num/'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:         >
  简直了，像我这种html根本看不懂的人居然能找到description标签.....

# The tags listed as entries in the sidebar
sidebar_tags:        [essay]

# Fallback image and color if not overwritten for tag or post
# image:               /public/img/001.jpg
color:               '#A85641'

# Fonts
font:                'Ubuntu Mono, consolas, 微软雅黑'
font_accent:         'Ubuntu Mono, consolas, 华文细黑, 微软雅黑'
load_google_fonts:   'consolas'

# About yourself
author:
  name:              'misty0703'

  # This photo will be used in the about section
  photo:             https://avatars3.githubusercontent.com/u/34191862?s=400&u=dc33126901288cc375836d82a6d0d26c4e247953&v=4
  photo2x:           https://avatars3.githubusercontent.com/u/34191862?s=400&u=dc33126901288cc375836d82a6d0d26c4e247953&v=4

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:             |
    这个Gitpage其实是我从酒石酸dalao哪里偷来的模板，不得不说，作为一个初学者就别想搞什么高端操作

    不知道从什么时候开始，就想弄一个自己的网页玩玩，直到我看到了943的一个视频(https://www.bilibili.com/video/av13994132)

    后来就想弄一个试试，倒是不看不知道一看吓一跳，之前选的模板复杂的不行，根本找不到主页到底在哪....

    期间玩坏了两三个模板，要么是主页没有套用layout要么就是直接404甚至还有css爆炸各种错位.....

    可能这就是人傻吧！@#￥%……&

  # Social media icons in sidebar
  # Comment/uncommet to show/hide
  # Icons appear in order, can be rearranged:
  social:
    # facebook:        _username_
    #twitter:         tartaric_acid
    # google:          _number_
    # vk:              _username_
    # youtube:         _string___string___string_
    # vimeo:           _username_
    # vine:            _username_
    # spotify:         user/_number_
    # soundcloud:      _username_
    # lastfm:          _username_
    # instagram:       _username_
    # flickr:          _string_@_string_
    # 500px:           _username_
    # dribbble:        _username_
    # behance:         _username_
    # deviantart:      _username_
    # ello:            _username_
    #twitch:          TartaricAcid
    steam:           mistywhite0703
    #reddit:          baka943
    # tumblr:          _username_
    # pinterest:       _username_
    # foursquare:      _number_
    # yelp:            _string_
    github:            misty0703
    # stackoverflow:   _number_/_username_
    # npm:             _username_
    # hackernews:      _username_
    # trello:          _firstname__lastname_
    # linkedin:        _firstname_-_lastname_-_string_
    # xing:            _firstname___lastname__counter_
    # blogger:         _number_
    # delicious:       _username_
    # stumbleupon:     _username_
    # paypal:          _username_

# Remove to disable Google Anaylics
# google_analytics_id: 'UA-84025722-2'

# Setting a disqus subdomain will enable the comment section
# disqus:            tartaric_acid

markdown: kramdown


compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [local]

sass:
  style:             compressed
